<a href="https://colab.research.google.com/github/jayanip613/MDS-LAB/blob/main/MDSWEEK2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### NumPy Array Indexing

In [2]:
# Create a 1D array for indexing demonstrations
arr_1d = np.array([102, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original 1D array:", arr_1d)

Original 1D array: [102   2   3   4   5   6   7   8   9]


In [3]:
# Accessing a single element by positive index (first element)
print("Element at index 0:", arr_1d[0])

Element at index 0: 102


In [4]:
# Accessing a single element by negative index (last element)
print("Element at last index:", arr_1d[-1])

Element at last index: 9


In [5]:
# Create a 2D array for indexing demonstrations
arr_2d = np.array([[102, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\nOriginal 2D array:\n", arr_2d)


Original 2D array:
 [[102  20  30]
 [ 40  50  60]
 [ 70  80  90]]


In [6]:
# Accessing an element in a 2D array (row 0, column 1)
print("Element at [0, 1]:", arr_2d[0, 1])

Element at [0, 1]: 20


In [7]:
# Accessing another element in a 2D array (row 2, column 2)
print("Element at [2, 2]:", arr_2d[2, 2])

Element at [2, 2]: 90


In [8]:
# Boolean indexing: select elements greater than 50
bool_indexed_arr = arr_2d[arr_2d > 50]
print("\nElements greater than 50 (Boolean indexing):", bool_indexed_arr)


Elements greater than 50 (Boolean indexing): [102  60  70  80  90]


### NumPy Array Slicing

In [9]:
# Create a 1D array for slicing demonstrations
arr_1d_slice = np.array([102, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original 1D array:", arr_1d_slice)

Original 1D array: [102   1   2   3   4   5   6   7   8   9]


In [10]:
# Basic slicing: elements from index 2 up to (but not including) index 5
print("Slice arr_1d_slice[2:5]:", arr_1d_slice[2:5])

Slice arr_1d_slice[2:5]: [2 3 4]


In [11]:
# Slice from the beginning up to (but not including) index 4
print("Slice arr_1d_slice[:4]:", arr_1d_slice[:4])

Slice arr_1d_slice[:4]: [102   1   2   3]


In [12]:
# Slice from index 6 to the end
print("Slice arr_1d_slice[6:]:", arr_1d_slice[6:])

Slice arr_1d_slice[6:]: [6 7 8 9]


In [13]:
# Slice with a step: every other element
print("Slice with step (arr_1d_slice[::2]):", arr_1d_slice[::2])

Slice with step (arr_1d_slice[::2]): [102   2   4   6   8]


In [14]:
# Reverse the array using slicing
print("Reversed array (arr_1d_slice[::-1]):", arr_1d_slice[::-1])

Reversed array (arr_1d_slice[::-1]): [  9   8   7   6   5   4   3   2   1 102]


In [15]:
# Create a 2D array for slicing demonstrations
arr_2d_slice = np.array([[102, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print("\nOriginal 2D array:\n", arr_2d_slice)


Original 2D array:
 [[102  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [16]:
# Slicing 2D: Get rows 0 and 1, all columns
print("Rows 0-1, all columns (arr_2d_slice[0:2, :]):\n", arr_2d_slice[0:2, :])

Rows 0-1, all columns (arr_2d_slice[0:2, :]):
 [[102  20  30  40]
 [ 50  60  70  80]]


In [17]:
# Slicing 2D: Get all rows, columns 1 and 2
print("All rows, columns 1-2 (arr_2d_slice[:, 1:3]):\n", arr_2d_slice[:, 1:3])

All rows, columns 1-2 (arr_2d_slice[:, 1:3]):
 [[ 20  30]
 [ 60  70]
 [100 110]]


In [18]:
# Slicing 2D: Get a sub-matrix (rows 1-2, cols 0-1)
print("Sub-matrix (rows 1-2, cols 0-1):\n", arr_2d_slice[1:3, 0:2])

Sub-matrix (rows 1-2, cols 0-1):
 [[ 50  60]
 [ 90 100]]


### NumPy Array Reshaping

In [19]:
# Create a 1D array for reshaping demonstrations
arr_reshape = np.arange(12) # Creates array [0, 1, ..., 11]
arr_reshape[0] = 102 # Set the first element to 102
print("Original 1D array:", arr_reshape)

Original 1D array: [102   1   2   3   4   5   6   7   8   9  10  11]


In [20]:
# Reshape the 1D array into a 3x4 2D array
arr_reshaped_3x4 = arr_reshape.reshape(3, 4)
print("\nReshaped to 3x4:\n", arr_reshaped_3x4)


Reshaped to 3x4:
 [[102   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [21]:
# Reshape the 1D array into a 4x3 2D array
arr_reshaped_4x3 = arr_reshape.reshape(4, 3)
print("\nReshaped to 4x3:\n", arr_reshaped_4x3)


Reshaped to 4x3:
 [[102   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


In [22]:
# Reshape with an inferred dimension (-1): 2 rows, columns inferred
arr_inferred_cols = arr_reshape.reshape(2, -1)
print("\nReshaped with inferred columns (2 rows):\n", arr_inferred_cols)


Reshaped with inferred columns (2 rows):
 [[102   1   2   3   4   5]
 [  6   7   8   9  10  11]]


In [23]:
# Reshape with an inferred dimension (-1): 3 columns, rows inferred
arr_inferred_rows = arr_reshape.reshape(-1, 3)
print("\nReshaped with inferred rows (3 columns):\n", arr_inferred_rows)


Reshaped with inferred rows (3 columns):
 [[102   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


In [24]:
# Flatten an array using the .flatten() method (returns a copy)
print("\nFlattened array (using .flatten()):", arr_reshaped_3x4.flatten())


Flattened array (using .flatten()): [102   1   2   3   4   5   6   7   8   9  10  11]


In [25]:
# Flatten an array using the .ravel() method (returns a view if possible)
print("\nRaveled array (using .ravel()):", arr_reshaped_3x4.ravel())


Raveled array (using .ravel()): [102   1   2   3   4   5   6   7   8   9  10  11]


### NumPy Array Joining

In [26]:
# Create two 1D arrays for joining demonstrations
arr_join_1d_1 = np.array([102, 2, 3])
arr_join_1d_2 = np.array([4, 5, 6])
print("1D Array 1:", arr_join_1d_1)
print("1D Array 2:", arr_join_1d_2)

1D Array 1: [102   2   3]
1D Array 2: [4 5 6]


In [27]:
# Concatenate 1D arrays along axis 0 (default behavior)
joined_1d_arr = np.concatenate((arr_join_1d_1, arr_join_1d_2))
print("Concatenated 1D arrays:", joined_1d_arr)

Concatenated 1D arrays: [102   2   3   4   5   6]


In [28]:
# Create two 2D arrays for joining demonstrations
arr_join_2d_1 = np.array([[102, 20], [30, 40]])
arr_join_2d_2 = np.array([[50, 60], [70, 80]])
print("\n2D Array 1:\n", arr_join_2d_1)
print("2D Array 2:\n", arr_join_2d_2)


2D Array 1:
 [[102  20]
 [ 30  40]]
2D Array 2:
 [[50 60]
 [70 80]]


In [29]:
# Concatenate 2D arrays along rows (axis=0)
joined_2d_rows = np.concatenate((arr_join_2d_1, arr_join_2d_2), axis=0)
print("\nJoined along rows (axis=0):\n", joined_2d_rows)


Joined along rows (axis=0):
 [[102  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]]


In [30]:
# Concatenate 2D arrays along columns (axis=1)
joined_2d_cols = np.concatenate((arr_join_2d_1, arr_join_2d_2), axis=1)
print("\nJoined along columns (axis=1):\n", joined_2d_cols)


Joined along columns (axis=1):
 [[102  20  50  60]
 [ 30  40  70  80]]


In [31]:
# Vertically stack arrays using np.vstack()
stacked_v = np.vstack((arr_join_2d_1, arr_join_2d_2))
print("\nVertically stacked (vstack):\n", stacked_v)


Vertically stacked (vstack):
 [[102  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]]


In [32]:
# Horizontally stack arrays using np.hstack()
stacked_h = np.hstack((arr_join_2d_1, arr_join_2d_2))
print("\nHorizontally stacked (hstack):\n", stacked_h)


Horizontally stacked (hstack):
 [[102  20  50  60]
 [ 30  40  70  80]]


In [33]:
# Depth stack (dstack) for creating 3D arrays from 2D arrays
stacked_d = np.dstack((arr_join_2d_1, arr_join_2d_2))
print("\nDepth stacked (dstack):\n", stacked_d)
print("Shape of dstacked array:", stacked_d.shape)


Depth stacked (dstack):
 [[[102  50]
  [ 20  60]]

 [[ 30  70]
  [ 40  80]]]
Shape of dstacked array: (2, 2, 2)


### NumPy Array Splitting

In [34]:
# Create a 1D array for splitting demonstrations
arr_split_1d = np.arange(10)
arr_split_1d[0] = 102 # Set the first element to 102
print("Original 1D array:", arr_split_1d)

Original 1D array: [102   1   2   3   4   5   6   7   8   9]


In [35]:
# Split the 1D array into 2 equal parts
split_1d_part1, split_1d_part2 = np.split(arr_split_1d, 2)
print("\nSplit into 2 equal parts:", split_1d_part1, split_1d_part2)


Split into 2 equal parts: [102   1   2   3   4] [5 6 7 8 9]


In [36]:
# Split the 1D array at specific indices (before index 2 and before index 7)
split_1d_at_indices = np.split(arr_split_1d, [2, 7])
print("\nSplit at indices [2, 7]:", split_1d_at_indices)


Split at indices [2, 7]: [array([102,   1]), array([2, 3, 4, 5, 6]), array([7, 8, 9])]


In [37]:
# Create a 2D array for splitting demonstrations
arr_split_2d = np.arange(16).reshape(4, 4)
arr_split_2d[0,0] = 102 # Set the first element to 102
print("\nOriginal 2D array:\n", arr_split_2d)


Original 2D array:
 [[102   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]]


In [38]:
# Vertically split (vsplit) the 2D array into 2 equal rows
vs_2d_part1, vs_2d_part2 = np.vsplit(arr_split_2d, 2)
print("\nVertical split (vsplit) into 2 parts:\n", vs_2d_part1, "\n", vs_2d_part2)


Vertical split (vsplit) into 2 parts:
 [[102   1   2   3]
 [  4   5   6   7]] 
 [[ 8  9 10 11]
 [12 13 14 15]]


In [39]:
# Horizontally split (hsplit) the 2D array into 2 equal columns
hs_2d_part1, hs_2d_part2 = np.hsplit(arr_split_2d, 2)
print("\nHorizontal split (hsplit) into 2 parts:\n", hs_2d_part1, "\n", hs_2d_part2)


Horizontal split (hsplit) into 2 parts:
 [[102   1]
 [  4   5]
 [  8   9]
 [ 12  13]] 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [40]:
# Unequal split using array_split (can handle non-divisible splits) along rows (axis=0)
split_unequal_rows = np.array_split(arr_split_2d, 3, axis=0)
print("\nUnequal split into 3 rows (array_split):\n")
for i, part in enumerate(split_unequal_rows):
    print(f"Part {i+1}:\n{part}")
    print("---")


Unequal split into 3 rows (array_split):

Part 1:
[[102   1   2   3]
 [  4   5   6   7]]
---
Part 2:
[[ 8  9 10 11]]
---
Part 3:
[[12 13 14 15]]
---


### Universal Functions (UFuncs)

In [41]:
# Create a 1D array for UFunc demonstrations
arr_ufunc = np.array([102, 2, 3, 4, 5])
print("Original array for UFuncs:", arr_ufunc)

Original array for UFuncs: [102   2   3   4   5]


In [42]:
# Element-wise addition with a scalar
print("Addition (arr_ufunc + 5):", arr_ufunc + 5)

Addition (arr_ufunc + 5): [107   7   8   9  10]


In [43]:
# Element-wise multiplication with a scalar
print("Multiplication (arr_ufunc * 2):", arr_ufunc * 2)

Multiplication (arr_ufunc * 2): [204   4   6   8  10]


In [44]:
# Element-wise square root using np.sqrt()
# Note: np.sqrt(102) is ~10.099
print("Square root (np.sqrt(arr_ufunc)):", np.sqrt(arr_ufunc))

Square root (np.sqrt(arr_ufunc)): [10.09950494  1.41421356  1.73205081  2.          2.23606798]


In [45]:
# Element-wise exponentiation (e^x) using np.exp()
print("Exponentiation (np.exp(arr_ufunc)):", np.exp(arr_ufunc))

Exponentiation (np.exp(arr_ufunc)): [1.98626484e+44 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02]


In [46]:
# Element-wise sine using np.sin()
print("Sine (np.sin(arr_ufunc)):", np.sin(arr_ufunc))

Sine (np.sin(arr_ufunc)): [ 0.99482679  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [47]:
# Element-wise cosine using np.cos()
print("Cosine (np.cos(arr_ufunc)):", np.cos(arr_ufunc))

Cosine (np.cos(arr_ufunc)): [ 0.1015857  -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [48]:
# Element-wise natural logarithm using np.log()
print("Logarithm (np.log(arr_ufunc)):", np.log(arr_ufunc))

Logarithm (np.log(arr_ufunc)): [4.62497281 0.69314718 1.09861229 1.38629436 1.60943791]


In [49]:
# Create a float array for rounding UFunc demonstrations
arr_float_ufunc = np.array([102.0, 2.3, 3.8, 4.1])
print("\nFloat array for rounding:", arr_float_ufunc)


Float array for rounding: [102.    2.3   3.8   4.1]


In [50]:
# Element-wise floor using np.floor()
print("Floor (np.floor(arr_float_ufunc)):", np.floor(arr_float_ufunc))

Floor (np.floor(arr_float_ufunc)): [102.   2.   3.   4.]


In [51]:
# Element-wise ceiling using np.ceil()
print("Ceil (np.ceil(arr_float_ufunc)):", np.ceil(arr_float_ufunc))

Ceil (np.ceil(arr_float_ufunc)): [102.   3.   4.   5.]


In [52]:
# Element-wise rounding using np.round()
print("Round (np.round(arr_float_ufunc)):", np.round(arr_float_ufunc))

Round (np.round(arr_float_ufunc)): [102.   2.   4.   4.]


In [53]:
# Create two arrays for binary UFunc demonstrations
arr_ufunc_a = np.array([102, 2, 3])
arr_ufunc_b = np.array([4, 5, 6])
print("\nArray A for binary UFuncs:", arr_ufunc_a)
print("Array B for binary UFuncs:", arr_ufunc_b)


Array A for binary UFuncs: [102   2   3]
Array B for binary UFuncs: [4 5 6]


In [54]:
# Element-wise addition of two arrays
print("Element-wise addition (arr_ufunc_a + arr_ufunc_b):", arr_ufunc_a + arr_ufunc_b)

Element-wise addition (arr_ufunc_a + arr_ufunc_b): [106   7   9]


In [55]:
# Element-wise maximum of two arrays using np.maximum()
print("Element-wise maximum (np.maximum(arr_ufunc_a, arr_ufunc_b)):", np.maximum(arr_ufunc_a, arr_ufunc_b))

Element-wise maximum (np.maximum(arr_ufunc_a, arr_ufunc_b)): [102   5   6]


### Mathematical Methods

In [56]:
# Create a 1D array for mathematical method demonstrations
arr_math = np.array([102, 2, 3, 4, 5])
print("Original array for mathematical methods:", arr_math)

Original array for mathematical methods: [102   2   3   4   5]


In [57]:
# Sum of all elements in the array using .sum()
print("\nSum of all elements (arr_math.sum()):", arr_math.sum())


Sum of all elements (arr_math.sum()): 116


In [58]:
# Minimum element in the array using .min()
print("Minimum element (arr_math.min()):", arr_math.min())

Minimum element (arr_math.min()): 2


In [59]:
# Maximum element in the array using .max()
print("Maximum element (arr_math.max()):", arr_math.max())

Maximum element (arr_math.max()): 102


In [60]:
# Mean (average) of elements in the array using .mean()
print("Mean of elements (arr_math.mean()):", arr_math.mean())

Mean of elements (arr_math.mean()): 23.2


In [61]:
# Standard deviation of elements in the array using .std()
print("Standard deviation (arr_math.std()):", arr_math.std())

Standard deviation (arr_math.std()): 39.412688312268166


In [62]:
# Product of all elements in the array using .prod()
print("Product of elements (arr_math.prod()):", arr_math.prod())

Product of elements (arr_math.prod()): 12240


In [63]:
# Create a 2D array for mathematical method demonstrations along axes
arr_math_2d = np.array([[102, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nOriginal 2D array for axis operations:\n", arr_math_2d)


Original 2D array for axis operations:
 [[102   2   3]
 [  4   5   6]
 [  7   8   9]]


In [64]:
# Sum along axis 0 (columns)
print("Sum along axis 0 (columns):", arr_math_2d.sum(axis=0))

Sum along axis 0 (columns): [113  15  18]


In [65]:
# Sum along axis 1 (rows)
print("Sum along axis 1 (rows):", arr_math_2d.sum(axis=1))

Sum along axis 1 (rows): [107  15  24]


In [66]:
# Minimum along axis 0 (columns)
print("Minimum along axis 0:", arr_math_2d.min(axis=0))

Minimum along axis 0: [4 2 3]


In [67]:
# Cumulative sum of the 1D array using np.cumsum()
print("\nCumulative sum (np.cumsum(arr_math)):", np.cumsum(arr_math))


Cumulative sum (np.cumsum(arr_math)): [102 104 107 111 116]
