<a href="https://colab.research.google.com/github/jayanip613/MDS-LAB/blob/main/MDSWEEK1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#checking version of numpy
import numpy as np
print (np.__version__)

2.0.2


In [ ]:
#which is better python list or numpy list according to size
import sys

# Memory usage for Python list
list_memory = sys.getsizeof(python_list_a) + sys.getsizeof(python_list_b) + sys.getsizeof(python_list_result)
print(f"Memory taken for Python lists: {list_memory / (1024 * 1024):.4f} MB")

# Memory usage for NumPy array
numpy_memory = numpy_array_a.nbytes + numpy_array_b.nbytes + numpy_array_result.nbytes
print(f"Memory taken for NumPy arrays: {numpy_memory / (1024 * 1024):.4f} MB")

Memory taken for Python lists: 23.3162 MB
Memory taken for NumPy arrays: 22.8882 MB


In [ ]:
#creating list and checking its type
list=[102,2,3,4,5]
print(type(list))


<class 'list'>


In [ ]:
#create an array
arr1=np.array(list)

In [ ]:
#print an array
print(arr1)

[102   2   3   4   5]


In [ ]:
#type of an array
type(arr1)

numpy.ndarray

In [ ]:
#dimension of an array
arr1.ndim

1

In [ ]:
#dataype of an array with its name only
arr1.dtype.name

'int64'

In [ ]:
#size of an array
arr1.size

5

In [ ]:
#shape of array with no.of rows and columns
arr1.shape

(5,)

In [ ]:
#check the bytes occupied
arr1.nbytes

40

In [ ]:
#creating a tuple
tuple=(102,2,3,5)

In [ ]:
#its type
type(tuple)

tuple

In [ ]:
# creating a tuple with single element
tuple2=(1,)

In [ ]:
#verifying its type
type(tuple2)

tuple

In [ ]:
#creating an array using tuple
arr2=np.array(tuple)

In [ ]:
#printing
print(arr2)

[102   2   3   5]


In [ ]:
#check dimension
arr2.ndim

1

In [ ]:
#create a 2d list
list1=[[102,2],[3,4]]

In [ ]:
#creating a matrix with existing list
matrix=np.array(list1)

In [ ]:
#print list
print(matrix)

[[102   2]
 [  3   4]]


In [ ]:
#dimension
matrix.ndim

2

In [ ]:
#its shape
matrix.shape

(2, 2)

In [ ]:
#size of the matrix
matrix.size

4

In [ ]:
#bytes occupied
matrix.nbytes

32

In [ ]:
#reducing the dimension to 1d
matrix.flatten()

array([102,   2,   3,   4])

In [ ]:
#create an array 1d
arr4=np.array([1,2,3,4])

In [ ]:
#print array
print(arr4)

[1 2 3 4]


In [ ]:
#create a 2d array
arr5=np.array([[1,2],[3,4]])

In [ ]:
#print array
print(arr5)

[[1 2]
 [3 4]]


In [ ]:
#create a matrix
arr6=np.matrix([[1,2,3],[4,5,6]])

In [ ]:

import numpy as np

# Create a 1D array with elements from 1 to 100
arr_1_to_100 = np.arange(1, 101)

# Print the array
print(arr_1_to_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
#create array from 1 to 100 with only elements divisible by 2
arr7=np.arange(0,100,2)

In [ ]:
#print
print(arr7)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [ ]:
#arrange a matrix and reshape to no.of rows and no.of columns
matrix2=np.arange(0,10).reshape(2,5)

In [ ]:
#print
print(matrix2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#reduce to 1d
matrix2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create a matrix with only 0's and int datatype
ai=np.zeros((3,3),dtype='int')

In [ ]:
#print
print(ai)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#its datatype name
ai.dtype.name

'int64'

In [ ]:
#create a matrix with only ones
b=np.ones((3,3),dtype='int')

In [ ]:
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#create a matrix of dimension filled with req number
c=np.full((3,3),2)

In [ ]:
print(c)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
d=np.full((10,10),6)

In [ ]:
print(d)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [ ]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.identity(3)

# Print the identity matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# an array of elements with equal difference
obj=np.linspace(0,1,5)

In [ ]:
print(obj)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# creates a random array
import random as random
x=np.random.random((3,3))
print(x)


[[0.8565596  0.48842964 0.08559801]
 [0.29898309 0.34925977 0.55010759]
 [0.49816747 0.84301033 0.12749706]]


In [ ]:
# arrange the req elements
arr9=np.arange(1,10)
print(arr9)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# change the element to so and so
arr9[0]=111

In [ ]:
print(arr9)

[111   2   3   4   5   6   7   8   9]


In [ ]:
#max element
arr9.max()

np.int64(111)

In [ ]:
#min element
arr9.min()

np.int64(2)